# Generated by Django 2.2.1 on 2020-06-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emarket_app', '0003_register_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_form',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_image/%Y/%m/%d'),
        ),
    ]
