# Generated by Django 2.2.1 on 2020-06-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emarket_app', '0004_register_form_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('product_image', models.ImageField(upload_to='product_type')),
            ],
        ),
    ]
