# Generated by Django 2.2.1 on 2020-06-11 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emarket_app', '0006_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('product_img', models.ImageField(max_length=200, upload_to='')),
                ('color', models.CharField(max_length=100)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emarket_app.brand_type_form')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emarket_app.product_category')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emarket_app.product_type')),
            ],
        ),
    ]
