# Generated by Django 2.2.1 on 2020-06-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emarket_app', '0007_product_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_info',
            name='product_img',
            field=models.ImageField(upload_to='product_image'),
        ),
    ]
