# Generated by Django 2.2.1 on 2020-06-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emarket_app', '0008_auto_20200611_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_email', models.CharField(max_length=200)),
                ('brand_id', models.CharField(max_length=100)),
                ('product_type_id', models.CharField(max_length=100)),
                ('product_category_id', models.CharField(max_length=100)),
                ('pro_id', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('quantity', models.CharField(default=1, max_length=100)),
                ('status', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
