# Generated by Django 2.2.1 on 2020-06-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emarket_app', '0009_cart_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_details',
            name='pro_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
