# Generated by Django 2.2.1 on 2020-06-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emarket_app', '0010_cart_details_pro_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_details',
            old_name='brand_id',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='cart_details',
            old_name='product_category_id',
            new_name='product_category_name',
        ),
        migrations.RenameField(
            model_name='cart_details',
            old_name='product_type_id',
            new_name='product_type_name',
        ),
    ]
