# Generated by Django 2.2.1 on 2020-06-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emarket_app', '0011_auto_20200613_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_details',
            name='pro_image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
