# Generated by Django 2.2.1 on 2020-06-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emarket_app', '0012_cart_details_pro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_details',
            name='pro_image',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
