# Generated by Django 2.2.1 on 2020-06-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emarket_app', '0013_auto_20200613_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_details',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
