# Generated by Django 2.2.1 on 2020-06-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emarket_app', '0015_auto_20200615_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='biling_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('Home', '1'), ('Work', '2')], max_length=50)),
                ('user_id', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField()),
            ],
        ),
    ]
