# Generated by Django 2.2.1 on 2020-06-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emarket_app', '0016_biling_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biling_address',
            name='email',
        ),
    ]
