# Generated by Django 2.2.1 on 2020-06-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emarket_app', '0017_remove_biling_address_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biling_address',
            name='address_type',
            field=models.CharField(choices=[('1', 'Home'), ('2', 'Work')], max_length=50),
        ),
    ]
