# Generated by Django 2.2.1 on 2020-06-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emarket_app', '0018_auto_20200615_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='biling_address',
            new_name='order_address',
        ),
    ]
