# Generated by Django 2.2.1 on 2020-06-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emarket_app', '0019_auto_20200615_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_address',
            name='address_type',
            field=models.CharField(choices=[('Home', '1'), ('Work', '2')], max_length=50),
        ),
    ]
