# Generated by Django 2.2.1 on 2020-06-15 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emarket_app', '0020_auto_20200615_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_form',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='register_form',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
    ]
