# Generated by Django 2.2.1 on 2020-06-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emarket_app', '0022_cart_details_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_details',
            name='order_address',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
