# Generated by Django 2.2.1 on 2020-06-17 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emarket_app', '0023_cart_details_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_details',
            name='order_address',
        ),
        migrations.AddField(
            model_name='cart_details',
            name='order_adres',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='emarket_app.order_address'),
        ),
    ]
